### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by bnhovde** [fedordead/fedordead.com#1]
Not sure what you guys reckon. Did you have any ideas?

I've lost my design chops long ago, but I did some sketches to kick things off. 

I've got a designer at work that could probably knock something up if we give him some ammo/direction.

![ideas](https://lh3.googleusercontent.com/n7AoBPA2OVbBMKgirwk37mPMx9ZJTBX01CvpuBNnjI06zdeSV0mxOGePebaH6_8JkB-m1jwmE01g-w=w708-h956-no)

**Comment by DaveOrDead** [comment]
They look cool! I think the ones with the crosses would be great as bones instead of plain lines?

The skull nerd is cool and I also like the simplicity of the black and white chunky one.

Graves might be a bit too much!

Nice work :)

**Comment by bnhovde** [comment]
Yeah bones could work. Some more idea materials based on the black/white idea we've already got rolling:

![ideas](https://lh3.googleusercontent.com/09WG_Lfu_8s_hsOuVN8qxmQaNsj7J27ag8SU2kHlOGKgCkjhCn61m91nEm6Gk1i8ldDPq4J8JCWfgF9gQg9aXRSJBBNUeVCxACZpbMzNGreZfbm4yF-7txP-fPAlC0YBdYyIrCdtOlzB6XlI6wnm0JcRhiwexg0BWVCz7c26IepHMrxXiC58FSn8Nrhrlxh9d5gQ55uTxNjgLUrpGCacAmp_dUX_a2nncIA9gU2xmIREhrkvUZWkb7lKGMo0AujYVdlwXh6HUcY4z-mX_zmZc-C20-W-brVz_Enkc5geXi1YJFTFJjUcxRGmvUMhWTSvjtvMPK7-R3V2XygZJr7vqoa-R6j65ObmEEh1Ma4rzJMBfC210tAX8ok7CvKY7l4TCTspBv7ZSIVCmODIWNKcQhJQoOjCfkvRbswnwDs1Rkp-CvJ6nWBt4bWcuctSkpewSNyJ145QAtL23ZAtLMo8b0h9KbAKYim6Pi_dT6U7jguf_z2hGQzTok5IAQnr2PDm2hbBtGHEFmkefl9rUaXWl1svi_QAq6oxBnlOkEUF7mXxa37aDRyEuPmrsXUPXUBI7NNs_A=w1280-h800-no)

**Comment by bnhovde** [comment]
More "ideas" by Joss and I

![screen shot 2016-01-28 at 07 44 33](https://cloud.githubusercontent.com/assets/4840600/12638180/17e6f68e-c593-11e5-8c2f-fe1299ce248b.png)

**Comment by chris-pearce** [comment]
All decided :smile:
